import hou

ENV_CTRL_NODE = "CTRL_NODE"
ENV_MULTIPARM_NODE = "MULTIPARM_NODE"
CTRL_BASE_NAME = "CTRL"
CTRL_COLOR_ACTIVE = hou.Color((0.8, 0.2, 0.2))
CTRL_COLOR_INACTIVE = hou.Color((0.996, 0.682, 0.682))

